#!/bin/bash

CACHE="/opt/julak/data/.script_permission"

if [[ ! -f $CACHE ]]; then
/opt/julak/data/permission-core
fi

STATUS=$(cat $CACHE | awk '{print $1}')

if [[ "$STATUS" != "VALID" ]]; then
echo -e "\e[1;31m❌ Client Name atau IP VPS tidak terdaftar!\033[0m"
echo -e "➥ Hubungi admin \033[1;96m「  ✦ https://wa.me/081250851741 ✦ 」 \033[0m"
exit
fi